### ISSUE TITLE
Global rate limit for all controllers

### ISSUE THREAD

**Issue by tsvetiligo** [thamtech/yii2-ratelimiter-advanced#4]
In my project I have parent controller for all controllers and set behaviors() in parent controller so rate limit settings is same. Rate limit works fine in one controller scope - if I reach limit in one action, other action throws TooManyRequestsHttpException to. But actions in other controllers don't throw TooManyRequestsHttpException for same rule! Rate limit in second controller also works fine in one controller scope, so I think issue in storage. I don't use cacheKeyPrefix and can't find any controller related settings for storage to set.

```
$behaviors['rateLimiterAuthenticated'] = [
            'class' => 'thamtech\ratelimiter\RateLimiter',
            'only' => $this->getAuthenticatedActions(),
            'except' => array_merge($this->getExcept(), $this->getOptional()),
            'components' => [
                'rateLimit' => [
                    'definitions' => [
                        'user' => [
                            'limit' => 1, // allowed hits per window
                            'window' => 60, // window in seconds
                            'identifier' => function($context, $rateLimitId) {
                                return Yii::$app->getUser()->getIdentity()->getId();
                            },
                        ],
                    ],
                ],
                'allowanceStorage' => [
                    'cache' => 'cache', // use Yii::$app->cache component
                ],
            ],
            'as rateLimitHeaders' => 'thamtech\ratelimiter\handlers\RateLimitHeadersHandler',
            'as retryAfterHeader' => 'thamtech\ratelimiter\handlers\RateLimitHeadersHandler',
            'as tooManyRequestsException' => 'thamtech\ratelimiter\handlers\TooManyRequestsHttpExceptionHandler',
];
```

**Comment by tyler-ham** [comment]
The rate limit has a separate scope for each object to which the behavior is attached. There is a ParentController _class_, but there isn't a ParentController _object_ to which your rate limit behavior is attached. You can define the rate limit behavior in a ParentController class, but it is still attached to the respective child controller objects.

So if you have ChildControllerA and ChildControllerB both inheriting the same rate limit behavior definition, the rate limit is still getting scoped to those two controllers separately. 

If you want the same limit shared across multiple controllers, I believe you can apply the rate limit behavior onto a Module instead of a controller. This should scope the rate limit to all controllers within that module.

The Application is just a special case of a Module, so if you want the limit to apply to all modules/controllers in your application, apply the rate limit behavior to the Application.

**Comment by tsvetiligo** [comment]
I look at code and now I see that you did it on purpose.
I believe scoped controllers allowance is wrong behavior for rate limit by default. 
If i wanted to use scope - I would set cacheKeyPrefix as controller name. But I do not want to and  I can't disable scope without overwriting code.

**Comment by tyler-ham** [comment]
Does defining the rate limit at a Module/Application level not work for your case?

I do understand the desire for more control over the scope. One solution might be to add a configuration property that lets you set the value used for the scope (so you could set it to a static or empty string if you'd like). However, the scope should continue to include the owning component by default.

If I define one rate limit on `FooController` and another rate limit on `BarController`, I don't think it is reasonable for the two rate limits to interact with each other by default. It could be especially problematic if they happen to have different window/limit values. However, if you know what you are doing and actually want them to share scope, then you would be able to override the default owning component scope. In this example, you might set it to `foobar` in both controllers.

In your use case, you could set it to an empty string, or some other sensible string that labels the collection of controllers over which it applies.

**Comment by tsvetiligo** [comment]
Please help me to define rate limit in Module. I try to move code from Controller behaviors() to Module behaviors() and get an error - "Call to a member function getId() on null" for code:
```
'identifier' => function($context, $rateLimitId) {
  return Yii::$app->getUser()->getIdentity()->getId();
},
```
In Controller same code works fine.

**Comment by tyler-ham** [comment]
I suppose this is because your authentication behaviors that set the user identity are still defined in the controller, and the module's `beforeAction` handlers are run before the controller's `beforeAction` handlers.

You could try moving your authentication logic up into the module as well, so it sets the user identity before the rate limit behavior is invoked.

Otherwise, I think the possible enhancement I described above (adding a configuration property for the scope) would probably work for you. I will try to find some time to work on that.
